apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockflow-backend
  template:
    metadata:
      labels:
        app: stockflow-backend
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: stockflow-backend
        image: 836533914314.dkr.ecr.ap-northeast-2.amazonaws.com/stockflow:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: stockflow-secret
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: stockflow-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stockflow-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: stockflow-secret
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: stockflow-secret
              key: JWT_EXPIRATION
        - name: JWT_REFRESH_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: stockflow-secret
              key: JWT_REFRESH_EXPIRATION
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: stockflow-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: stockflow-config
              key: REDIS_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: stockflow-backend-service
spec:
  selector:
    app: stockflow-backend
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
